app:
  couchbase:
    connection-string: couchbase://127.0.0.1
    user-name: tester1
    password: tester
    bucket-PIES: PRODUCTS
    bucket-ACES: CATALOG

logging:
  level:
    org:
      hibernate:
        type: trace